# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5625d6b76439da1e361385c858003ff3052c53d28b95f1eaf3795174c05e9f7739302d5013cd55d622b2481af8f561ad183c341c766dc3fa9e2a8a3cd05d06a

test:
  secret_key_base: ad0d3b2b2ef417d4ff0fb6317d0e2c35637cec2b0f4fee9d21e47d1762bdeda575a4149539a2bd6dbd1d2a3c62a7ce79d12057665eed8b9920da86198543b12a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
